### ISSUE TITLE
启动node服务尝试登录时，出现以下报错

### ISSUE THREAD

**Issue by Graicaa** [HibiKier/zhenxun_bot_webui#1]
![1652947901(1)](https://user-images.githubusercontent.com/50552632/169245558-eec1b524-ea2f-48bb-9f0d-b42b8875aa74.png)

**Comment by Graicaa** [comment]
![1652947987(1)](https://user-images.githubusercontent.com/50552632/169245823-e48d295f-d899-448a-b0ba-94ab05b2e59b.png)

这里改了一下我服务器地址

**Comment by ChenFu0420** [comment]
同样出现这样的问题，不过我没有修改任何配置，Bot 和Web服务在同一台服务器

**Comment by sdfsddftd** [comment]
你bot的端口是8080吗？这里的端口要和bot设置的端口保持一致

**Comment by Akasteria** [comment]
应该是端口错了，bot默认的端口改到14514了，可能web没改

**Comment by Graicaa** [comment]
感谢大家，确实是端口错了，一直没回复

**Comment by wjiajian** [comment]
> 

请问一下bot的端口在哪里查看
