### ISSUE TITLE
SvgIcon error报错

### ISSUE THREAD

**Issue by ayakasuki** [HibiKier/zhenxun_bot_webui#13]
import SvgIcon from "../../components/svgIcon/SvgIcon.vue";
温馨提醒 文件夹是大写的S“SvgIcon”，import是svgIcon导致报错

**Comment by ayakasuki** [comment]
> ![@U5U$KAPCOC2SG@%{HYMRE7](https://user-images.githubusercontent.com/93612024/229579660-28a729a7-69af-4ad3-a995-d862fe8f0477.png) 同，无法部署

改下文件夹名

**Comment by ayakasuki** [comment]
![image](https://user-images.githubusercontent.com/20859971/229659115-5e02fc52-c8da-4955-8283-9d7be157a179.png)
![image](https://user-images.githubusercontent.com/20859971/229659165-443d0854-5ade-4bd5-a979-856fed0162c8.png)

改了一下代码，比之前死亡蓝条好看点

**Comment by HibiKier** [comment]
擦，来点ui

**Comment by QAQATT** [comment]
![@J7$UY}UK`YBCYC(WIBIWNO](https://user-images.githubusercontent.com/93612024/229771938-c9b29e0f-8aad-42f1-ab75-4a15aac786e8.png)
大佬帮帮，网页部署成功了，但是post请求404

**Comment by QAQATT** [comment]
谢谢大佬指引，已经部署成功了
