### ISSUE TITLE
webui出现未知错误

### ISSUE THREAD

**Issue by 123xuwu** [HibiKier/zhenxun_bot_webui#14]
看起来像是请求路径错了
![Screenshot_2023-06-06-21-56-29-939_mark via](https://github.com/HibiKier/zhenxun_bot_webui/assets/94461937/e7dfddf3-5dd8-4dbe-a138-55300e6161be)
![Screenshot_2023-06-06-21-56-38-652_com termux](https://github.com/HibiKier/zhenxun_bot_webui/assets/94461937/4115b034-de3d-4f0a-a014-97c91bc9db53)

**Comment by AlanFH1842** [comment]
webui插件在重写，没有启动
![Uploading 2B07B3D8-14C3-43DA-B77F-CDA0E8E9C3A5.png…]()
