### ISSUE TITLE
登录提示发生错误

### ISSUE THREAD

**Issue by Nenot233** [HibiKier/zhenxun_bot_webui#18]
真寻版本-dev
![1723604583940](https://github.com/user-attachments/assets/5786b94f-a828-4bd1-9dcf-9d1ce6a881d7)
![1723604571538](https://github.com/user-attachments/assets/58ba9622-b744-42a2-9681-cc24a6e9eea4)

**Comment by HibiKier** [comment]
用f12看login的报错，别单独调接口，你真寻的端口是8080吗

**Comment by Nenot233** [comment]
![1723607871239](https://github.com/user-attachments/assets/4e3fe661-c18f-441f-822d-723cba86d70e)
![1723607768735](https://github.com/user-attachments/assets/088d72d6-f93b-444f-bd47-c44b6e5f8268)
真寻的端口是8080

**Comment by HibiKier** [comment]
看一下真寻里的报错

**Comment by Nenot233** [comment]
![QQ_1723609709514](https://github.com/user-attachments/assets/626dc1b9-8772-48e0-9965-4c9939a581aa)
这是我没连上真寻的webui api？

**Comment by HibiKier** [comment]
你连上了，登录报了500，你看一下登录的时候真寻的报错

**Comment by Nenot233** [comment]
登陆的时候真寻没有报错
![1723610963047](https://github.com/user-attachments/assets/09ac57ca-5358-4de0-af92-ad3d26f526ca)

**Comment by HibiKier** [comment]
把你真寻的HOST改成0.0.0.0试试

**Comment by Nenot233** [comment]
![QQ_1723611736361](https://github.com/user-attachments/assets/e243427f-9100-43d6-a572-433ec007591b)
还是登不上

**Comment by HibiKier** [comment]
vue.config.js 你的截个图我看看

**Comment by Nenot233** [comment]
![1723613855058](https://github.com/user-attachments/assets/68dd5294-cb79-41cf-b528-c7563bdfd53d)

**Comment by Nenot233** [comment]
![QQ_1723614788752](https://github.com/user-attachments/assets/f0fb6ce4-cfbf-4b3f-b1ec-3ba064e776cf)
 说是Login.vue 文件的第 149 行，JavaScript 代码尝试读取一个未定义对象的 'suc' 属性

**Comment by HibiKier** [comment]
你转发前端接口转发到后端没成功，一般本地部署是不会有这个问题的

**Comment by Nenot233** [comment]
Node一般推荐什么版本？
````
D:\BOT\zhenxun_bot_webui-dev>npm install
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@achrinza/node-ipc@9.2.2',
npm warn EBADENGINE   required: { node: '8 || 10 || 12 || 14 || 16 || 17' },
npm warn EBADENGINE   current: { node: 'v18.20.4', npm: '10.7.0' }
npm warn EBADENGINE }

up to date, audited 1190 packages in 8s

118 packages are looking for funding
  run `npm fund` for details

38 vulnerabilities (18 moderate, 15 high, 5 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
````

**Comment by HibiKier** [comment]
20可以的，我开发环境就是20

**Comment by Nenot233** [comment]
我在尝试一下npm install

**Comment by HibiKier** [comment]
你webui加载成功了吗

**Comment by HibiKier** [comment]
620174107 进群当面蕉流

**Comment by HibiKier** [comment]
已解决，疑似npm问题
